### ISSUE TITLE
TODOS

### ISSUE THREAD

**Issue by richardjimenezyolo** [richardjimenezyolo/rpt-builder#6]
## TODOS
- [x] Poder guardar archivos.
- [x] Poder crear nuevos archivos.
- [x] Cambiar el zoom del canvas al comento de `resize` la ventana.
- [ ] Poder ocultar los paneles laterales en pantallas pequeñas.
- [ ] Poder cambiar el tamaño de la letra en `RptDataTable` desde el panel de propiedades.
- [ ] Poder cambiar el tamaño de las imagenes.
- [ ] #8
